#!/bin/bash
full_version=`uname -r`

# First check for a fully qualified version.
this="/usr/lib/linux-tools/$full_version/`basename $0`"
if [ -f "$this" ]; then
	exec "$this" "$@"
fi

# Removing flavour from version i.e. generic or server.
flavour_abi=${full_version#*-}
flavour=${flavour_abi#*-}
version=${full_version%-$flavour}
this="$0_$version"
if [ -f "$this" ]; then
	exec "$this" "$@"
fi

flavour="-$flavour"
cld=""
std=""
lts=":"
# Give them a hint as to what to install.
		echo "WARNING: `basename $0` not found for kernel $version" >&2
		echo "" >&2
		echo "  You may need to install the following packages for this specific kernel:" >&2
		echo "    linux-tools-$version$flavour" >&2
$cld		echo "    linux-cloud-tools-$version$flavour" >&2
		echo "" >&2
		echo "  You may also want to install one of the following packages to keep up to date:" >&2
$std		echo "    linux-tools$flavour" >&2
$std $cld	echo "    linux-cloud-tools$flavour" >&2
$lts		echo "    linux-tools$flavour-lts-<series>" >&2
$lts $cld	echo "    linux-cloud-tools$flavour-lts-<series>" >&2

exit 2
